name: CI


on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - uses: pyodide/setup-emsdk@v15
        with:
          version: 3.1.69
          actions-cache-folder: 'emsdk-cache'
      
      - name: Build-WASM
        run: |
          emcc -v
          mkdir wasm-cpp/build-wasm
          cd wasm-cpp/build-wasm
          emcmake cmake ..                      \
            -DCMAKE_BUILD_TYPE=Release          \
            -DCMAKE_VERBOSE_MAKEFILE=ON
          emmake make
      
      - name: Deno
        run: |
          ./deno.sh task install
      
      - name: Test
        run: |
          ./run_tests.sh
      
      - name: Build-App
        run: |
          ./build.ts --no-pyodide --minify
      
      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: pagebuild
          path: |
            static/*
          if-no-files-found: error

      - name: Compare bundle size
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ./deno.sh run             \
            --allow-read=./         \
            --allow-net=*.github.io \
            .github/scripts/compare_bundle_size.ts \
            https://${{ github.repository_owner }}.github.io/${{ github.repository }} \
            ./static/ \
            > bundle_comparison.md
      
      - name: Comment to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: bundle_comparison.md
          comment-tag: bundlecomparison



  deploy:
    needs:   build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.inputs.release == 'true' }}

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pagebuild
          path: artifact/

      - name: Release
        run: |
          TAGNAME=v$(date +%F)
          echo $TAGNAME

          git fetch origin gh-pages
          git checkout gh-pages
          cp artifact/index.* ./
          rm -r artifact
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./index.*
          git commit -m "$TAGNAME"
          git tag --force $TAGNAME
          git push origin gh-pages
          git push origin --tags
